---
layout: post
title: "测四"
date: 2017-08-27
---

本文是 https://pymotw.com/3/asyncio/tasks.html 的学习笔记，强烈推荐直接阅读原文。

Task 是跟事件循环交互的一种主要方式。Task 包装并追踪 Coroutine 的完成状态。Task 是 Future 的子类，因此其他 Coroutine 可以 wait Task 并且在 Task 完成时还可以获取 Coroutine 的结果。

## 启动 Task

可以使用 create_task 来创建一个 Task 实例:

```python
# asyncio_create_task.py
import asyncio


async def task_func():
    print('in task_func')
    return 'the result'


async def main(loop):
    print('creating task')
    task = loop.create_task(task_func())
    print('waiting for {!r}'.format(task))
    return_value = await task
    print('task completed {!r}'.format(task))
    print('return value: {!r}'.format(return_value))


event_loop = asyncio.get_event_loop()
try:
    event_loop.run_until_complete(main(event_loop))
finally:
    event_loop.close()
```

可以看到 await task 返回的是 task_func 函数的返回值:

```
$ python3.6 asyncio_create_task.py
creating task
waiting for <Task pending coro=<task_func() running at asyncio_create_task.py:5>>
in task_func
task completed <Task finished coro=<task_func() done, defined at asyncio_create_task.py:5> result='the result'>
return value: 'the result'
```

取消 Task
可以在 Task 完成之前取消 task 的操作:

```python
# asyncio_cancel_task.py
import asyncio


async def task_func():
    print('in task_func')
    return 'the result'


async def main(loop):
    print('creating task')
    task = loop.create_task(task_func())

    print('canceling task')
    task.cancel()

    print('canceled task {!r}'.format(task))
    try:
        await task
    except asyncio.CancelledError:
        print('caught error from canceled task')
    else:
        print('task result: {!r}'.format(task.result()))


event_loop = asyncio.get_event_loop()
try:
    event_loop.run_until_complete(main(event_loop))
finally:
    event_loop.close()
```

当在事件循环启动前取消一下 task 时， await task 会抛出 CancelledError 异常:

```
$ python3.6 asyncio_cancel_task.py
creating task
canceling task
canceled task <Task cancelling coro=<task_func() running at asyncio_cancel_task.py:5>>
caught error from canceled task
```
